name: Run Unit Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'resources/js/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.mjs'
      - 'vitest.config.js'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm run test:run
      env:
        LARAVEL_BYPASS_ENV_CHECK: 1
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          coverage/
          test-results.xml
        retention-days: 7 